version: '3.7'
services:
  app:
    image: 'eu.gcr.io/at-artefacts/retailer-tools-design-system'
    build:
      context: .
      args:
        GO_DEPENDENCY_LABEL_BASE_NODEJS20: '${GO_DEPENDENCY_LABEL_BASE_NODEJS20:-latest}'
        GO_PIPELINE_COUNTER: '${GO_PIPELINE_COUNTER}'
        GO_TO_REVISION_RETAILER_TOOLS_STORYBOOK: '${GO_TO_REVISION_RETAILER_TOOLS_STORYBOOK-HEAD}'
        GO_FROM_REVISION_RETAILER_TOOLS_STORYBOOK: '${GO_FROM_REVISION_RETAILER_TOOLS_STORYBOOK-master}'
        GO_MATERIAL_BRANCH_RETAILER_TOOLS_STORYBOOK: '${GO_MATERIAL_BRANCH_RETAILER_TOOLS_STORYBOOK-master}'
        NX_BRANCH: '${NX_BRANCH-master}'
        NX_CLOUD_ACCESS_TOKEN: '${NX_CLOUD_ACCESS_TOKEN-YjNkOTg1NDEtOTkyMS00N2E2LTg5YzctZWQ1ZDczOTAyYTc0fHJlYWQtd3JpdGU=}'
        NX_SKIP_NX_CACHE: '${NX_SKIP_NX_CACHE-false}'
        GO_PIPELINE_NAME: '${GO_PIPELINE_NAME}'
        GO_STAGE_NAME: '${GO_STAGE_NAME}'
        GO_STAGE_COUNTER: '${GO_STAGE_COUNTER}'
        GO_JOB_NAME: '${GO_JOB_NAME}'
        GO_API_AUTH_TOKEN: '${GO_API_AUTH_TOKEN}'
    environment:
      FORCE_COLOR: 1
      DEBUG_COLORS: 1
      MOCHA_COLORS: 1
      CYPRESS_PROCESS_PROFILER_INTERVAL: 1000
    ports:
      - '8080:8080'
