/* 🤖 this file was generated by svg-to-ts */

import { IconModel } from './dist/icon.model';

export type IconModelNameSubset<
  T extends Readonly<IconModel[]>
> = T[number]['name'];

export * from './dist/icon-add.icon';
export * from './dist/icon-calendar.icon';
export * from './dist/icon-close.icon';
export * from './dist/icon-delete.icon';
export * from './dist/icon-download.icon';
export * from './dist/icon-expand.icon';
export * from './dist/icon-launch.icon';
export * from './dist/icon-open.icon';
export * from './dist/icon-print.icon';
export * from './dist/icon-refresh.icon';
export * from './dist/icon-tick.icon';
export * from './dist/icon-bike.icon';
export * from './dist/icon-car.icon';
export * from './dist/icon-caravan.icon';
export * from './dist/icon-farm.icon';
export * from './dist/icon-motorhome.icon';
export * from './dist/icon-plant.icon';
export * from './dist/icon-truck.icon';
export * from './dist/icon-van.icon';
export * from './dist/icon-down.icon';
export * from './dist/icon-left.icon';
export * from './dist/icon-right.icon';
export * from './dist/icon-up.icon';
export * from './dist/icon-alert.icon';
export * from './dist/icon-lock.icon';
export * from './dist/icon-search.icon';
export * from './dist/icon-sterling.icon';
export * from './dist/icon-email.icon';
export * from './dist/icon-mute.icon';
export * from './dist/icon-play.icon';
export * from './dist/icon-stop.icon';
export * from './dist/icon-volume.icon';
export * from './dist/icon-critical-filled.icon';
export * from './dist/icon-critical.icon';
export * from './dist/icon-excellent.icon';
export * from './dist/icon-information-filled.icon';
export * from './dist/icon-information.icon';
export * from './dist/icon-success.icon';
export * from './dist/icon-warning-filled.icon';
export * from './dist/icon-warning.icon';
export * from './dist/complete-icon-set';
export * from './dist/icon.model';
