#!/bin/sh
#
# Retailer Tools post-checkout hook

BASELOG="\033[96m[\033[34mRetailer\033[96m-\033[34mTools\033[96m-\033[34mDesign\033[96m-\033[34mSystem\033[0m\033[96m]\033[0m "
ENDLOG="\033[0m\n"

source ./.githooks/common.sh

output () {
  printf "${BASELOG}$1${ENDLOG}"
}

printf "$(cat tools/ascii)"

output "\033[96m====================================================="
output "      Useful Links        "
output "\033[96m====================================================="
output "Portal Front End Channel:          \033[1mhttps://autotrader.enterprise.slack.com/archives/CA5K01DJA"
output "Retail Tools Design System Channel:          \033[1mhttps://autotrader.enterprise.slack.com/archives/C01E08Q9DKL"
output "RTDS Storybook:                         \033[1mhttps://app.retailer-tools-design-system.preprod.k8.atcloud.io/"

exit 0
