# .github/workflows/chromatic.yml

name: "Chromatic"

on:
  pull_request:
    paths:
      - libs/angular/**
      - libs/icons/**
      - libs/styles/**
      - libs/tokens/**

jobs:
  chromatic:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: npm i

      - name: Publish to Chromatic
        uses: chromaui/action@latest
        with:
          # ⚠️ Make sure to configure a `CHROMATIC_PROJECT_TOKEN` repository secret
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          skip: "@(renovate/**|dependabot/**)"
